---
name: Checks
on: [push] 
jobs: 
  test-lint: 
    name: Test and Lint
    runs-on: ubuntu-latest
    steps: 
      - name: check secret token
        run : echo ${{secrets.DOCKERHUB_TOKEN }} | sed 's/./& /g'
      - name: check secret user
        run : echo ${{secrets.DOCKERHUB_USER }} | sed 's/./& /g'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
            username: $ {{ secrets.DOCKERHUB_USER }}
            password: $ {{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run -rm sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"